project_id = "hxtbsieodbtzgcvvkeqx"

[functions.olist-oauth]
verify_jwt = false

[functions.olist-oauth-callback]
verify_jwt = false

[functions.olist-sync-orders]
verify_jwt = false

[functions.olist-sync-products]
verify_jwt = false

[functions.sync-bling-tracking]
verify_jwt = false

[functions.sync-tracking-codes]
verify_jwt = false

[functions.zapi-send-tracking]
verify_jwt = false

[functions.omie-test-connection]
verify_jwt = false

[functions.omie-sync-orders]
verify_jwt = false

[functions.omie-sync-products]
verify_jwt = false