# ============================================================
# RAILWAY.YML - CONFIGURAÇÃO MÁXIMA PRIORIDADE
# ============================================================
# Este arquivo tem PRIORIDADE ABSOLUTA sobre qualquer detecção
# ============================================================

version: 1

build:
  builder: dockerfile
  dockerfilePath: Dockerfile
  
deploy:
  startCommand: node backend/server-main.js
  healthcheckPath: /health
  healthcheckTimeout: 100
  restartPolicyType: on-failure
  restartPolicyMaxRetries: 10
