-- Criar tabela para mapear clientes aos grupos de WhatsApp
CREATE TABLE customer_whatsapp_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_phone TEXT NOT NULL,
  customer_name TEXT,
  whatsapp_group_name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(customer_phone, whatsapp_group_name)
);

-- Adicionar RLS
ALTER TABLE customer_whatsapp_groups ENABLE ROW LEVEL SECURITY;

-- Política para permitir acesso público
CREATE POLICY "Public can manage customer whatsapp groups" 
ON customer_whatsapp_groups 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- Criar índices para performance
CREATE INDEX idx_customer_whatsapp_groups_phone ON customer_whatsapp_groups(customer_phone);
CREATE INDEX idx_customer_whatsapp_groups_group ON customer_whatsapp_groups(whatsapp_group_name);

-- Adicionar alguns dados exemplo baseado no que você mostrou
INSERT INTO customer_whatsapp_groups (customer_phone, customer_name, whatsapp_group_name) VALUES
('553182125522', 'Gláucia Aguiar', '13 Anos MANIA DE MULHER - J'),
('5564984052726', 'Haline Osório Siqueira', '13 Anos MANIA DE MULHER - J');

-- Atualizar trigger para atualizar timestamp
CREATE TRIGGER update_customer_whatsapp_groups_updated_at
  BEFORE UPDATE ON customer_whatsapp_groups
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();