-- Criar integração ME para BIQUINI DA TAHY com dados válidos
INSERT INTO integration_me (
  tenant_id,
  client_id,
  client_secret,
  access_token,
  environment,
  from_name,
  from_email, 
  from_phone,
  from_document,
  from_address,
  from_number,
  from_complement,
  from_district,
  from_city,
  from_state,
  from_cep,
  is_active
) VALUES (
  '3c92bf57-a114-4690-b4cf-642078fc9df9',
  '19768',
  'NuwrKOUEWETpShw3YReadI3WEyO7H93KsQLgYgu0',
  'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTk3NDY1MDZiZDdjOTMxNjdjNDkwZmYwNTUyNzEyMjg2MjhlODNjOWNmNDgzYmI0M2Y5NDlhMjUyZjQ1OGYzMGJlZWVlNmRhZDNiNzJhNDYiLCJpYXQiOjE3NTgwNDEwMDguNjAzNTg2LCJuYmYiOjE3NTgwNDEwMDguNjAzNTg3LCJleHAiOjE3ODk1NzcwMDguNTkyMTgyLCJzdWIiOiI1Mjc3NGEzMS04YTQ3LTQ1MTktODZkMi00ZjE1NTI1YTIyZmEiLCJzY29wZXMiOlsiY2FydC1yZWFkIiwiY2FydC13cml0ZSIsImNvbXBhbmllcy1yZWFkIiwiY29tcGFuaWVzLXdyaXRlIiwiY291cG9ucy1yZWFkIiwiY291cG9ucy13cml0ZSIsIm5vdGlmaWNhdGlvbnMtcmVhZCIsIm9yZGVycy1yZWFkIiwicHJvZHVjdHMtcmVhZCIsInByb2R1Y3RzLWRlc3Ryb3kiLCJwcm9kdWN0cy13cml0ZSIsInB1cmNoYXNlcy1yZWFkIiwic2hpcHBpbmctY2FsY3VsYXRlIiwic2hpcHBpbmctY2FuY2VsIiwic2hpcHBpbmctY2hlY2tvdXQiLCJzaGlwcGluZy1jb21wYW5pZXMiLCJzaGlwcGluZy1nZW5lcmF0ZSIsInNoaXBwaW5nLXByZXZpZXciLCJzaGlwcGluZy1wcmludCIsInNoaXBwaW5nLXNoYXJlIiwic2hpcHBpbmctdHJhY2tpbmciLCJlY29tbWVyY2Utc2hpcHBpbmciLCJ0cmFuc2FjdGlvbnMtcmVhZCIsInVzZXJzLXJlYWQiLCJ1c2Vycy13cml0ZSIsIndlYmhvb2tzLXJlYWQiLCJ3ZWJob29rcy13cml0ZSIsIndlYmhvb2tzLWRlbGV0ZSIsInRkZWFsZXItd2ViaG9vayJdfQ.C-9nN6ScVacCltuP6aiPYqubAh5M_qOnzmIMYkTeShzuF6jjEDj3KTcIEBEnubucOhPO3EEHHvM1l_rhvtTjz4ZeOgirD7U6X-BNfeDkgB3NssE7m1sAr8taaPv42vrw1r4YpL7aVUDfisTYuf3CsxNwfKEheBflojnq3uJ2ttS55eNOlITu_a0O4TpBQAVEvs83-j64v9iWQRYOFoGwf3AYnLLhuHUC7sBRX_gziukvcLc_8nl6yZiyPAa03D496tUc3HES1qtJpm01z5us2y4zWcAXOy2EA2NYxGCwdVHRXRc4o_przed93QY7HpbO2g_1wkP9lD2WBibmBYfIEJvYSn1fzIEDiHoDPkUv2GVeIh35JaAo7iIjTGrqRANmnDHbgR-0mi81iKvrPrvcPRCiAXdhgRdcl03BHmpkLNwC0RqzqKzPqQgBa6B-UV-8LGIGSJg7heE4a3mBI8kbbSOPMrvYnlXXLsbB21NRoHw2a6hSSPuIr-GvPsq3OEqCiDGXhIvKjSVqgDbjX5m979DPe1-occZe1MiR4jfyLI7Z-6xVr_oZrJLnqpihoJo0iaLa5WFMdaXMVKP7jObduCNmgc8AGY1OICtsv-SMUBxoyvGrHar8axnPi2t2LJ_4-AVQs0lt3epREAeExtMbC_tHnvx4HWMdXSGbMtFsjuFo',
  'sandbox',
  'BIQUINI DA TAHY LTDA',
  'contato@biquinidatahy.com',
  '31888888888',
  '22333444000182', -- CNPJ válido diferente para sandbox
  'Rua das Águas',
  '456',
  'Loja 1',
  'Praia Grande',
  'Guarujá',
  'SP',
  '11470000',
  true
) ON CONFLICT (tenant_id) DO UPDATE SET
  from_name = EXCLUDED.from_name,
  from_email = EXCLUDED.from_email,
  from_phone = EXCLUDED.from_phone,
  from_document = EXCLUDED.from_document,
  from_address = EXCLUDED.from_address,
  from_number = EXCLUDED.from_number,
  from_complement = EXCLUDED.from_complement,
  from_district = EXCLUDED.from_district,
  from_city = EXCLUDED.from_city,
  from_state = EXCLUDED.from_state,
  from_cep = EXCLUDED.from_cep,
  updated_at = now();